# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c078253472283c3f932fa57ab9900a2c0d55d9488e2eb50d2e18f6980544488a6bfd5b7c3529b05c5cce37cec2190dc6427eaee3a7830630205db10cc8ec3d6

test:
  secret_key_base: 320a2db7933846bbdc7e5abfb7ee477ded247e125750bdcb877e17dff578b0245d4333a9417cca07caf8265419070f7c8323ed31ad5ffcc1523a893928858e9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
